apiVersion: v1
kind: Pod
metadata:
  name: petclinic-imagecheck
spec:
  containers:
    - name: app
      image: amank47/petclinic:v1.0.0
      command: ["sh", "-c", "sleep 3600"]
  restartPolicy: Never
